CREATE DATABASE ORDEMSERVICO;


USE ORDEMSERVICO;

CREATE TABLE CLIENTE (
    IDCLIENTE INT AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    ENDEREÇO VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(45) NOT NULL,
    CONSTRAINT UK_CLIENTE_CPF UNIQUE (CPF),
    CONSTRAINT UK_CLIENTE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE)
);
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;

CREATE TABLE VEICULO (
    IDVEICULO INT AUTO_INCREMENT,
    PLACA VARCHAR(10) NOT NULL,
    MODELO VARCHAR(45),
    ANO INT,
    MARCA VARCHAR(45),
    CLIENTE_ID INT NOT NULL,
    CONSTRAINT PK_VEICULO PRIMARY KEY (IDVEICULO),
    CONSTRAINT FK_CLIENTE_VEICULO FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(IDCLIENTE)
);
ALTER TABLE VEICULO AUTO_INCREMENT = 1;

CREATE TABLE MECANICO (
    IDMECANICO INT AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    ENDEREÇO VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(45) NOT NULL,
    ESPECIALIDADE VARCHAR(45) NOT NULL,
    CONSTRAINT UK_MECANICO_CPF UNIQUE (CPF),
    CONSTRAINT UK_MECANICO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT PK_MECANICO PRIMARY KEY (IDMECANICO)
);
ALTER TABLE MECANICO AUTO_INCREMENT = 1;

CREATE TABLE EQUIPE (
    IDEQUIPE INT AUTO_INCREMENT,
    NOMEEQUIPE VARCHAR(45) NOT NULL,
    CONSTRAINT PK_EQUIPE PRIMARY KEY (IDEQUIPE)
);

CREATE TABLE EQUIPE_MECANICO (
    EQUIPE_ID INT NOT NULL,
    MECANICO_ID INT NOT NULL,
    CONSTRAINT PK_EQUIPE_MECANICO PRIMARY KEY (EQUIPE_ID, MECANICO_ID),
    CONSTRAINT FK_EQUIPE_EQUIPE_MECANICO FOREIGN KEY (EQUIPE_ID) REFERENCES EQUIPE(IDEQUIPE),
    CONSTRAINT FK_MECANICO_EQUIPE_MECANICO FOREIGN KEY (MECANICO_ID) REFERENCES MECANICO(IDMECANICO)
);

CREATE TABLE ORDEM_SERVICO (
    IDORDEM_SERVICO INT AUTO_INCREMENT,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE,
    STATUS ENUM('EM ESPERA', 'ATENDENDO', 'FINALIZADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    VEICULO_ID INT NOT NULL,
    MECANICOS_ID INT NOT NULL,
    CONSTRAINT PK_ORDEM_SERVICO PRIMARY KEY (IDORDEM_SERVICO),
    CONSTRAINT FK_VEICULO_ORDEM_SERVICO FOREIGN KEY (VEICULO_ID) REFERENCES VEICULO(IDVEICULO),
    CONSTRAINT FK_EQUIPE_MECANICO_ORDEM_SERVICO FOREIGN KEY (MECANICOS_ID) REFERENCES EQUIPE_MECANICO(EQUIPE_ID)
);
ALTER TABLE ORDEM_SERVICO AUTO_INCREMENT = 1;

CREATE TABLE SERVICO (
    IDSERVICO INT AUTO_INCREMENT,
    DESCRICAO VARCHAR(45) NOT NULL,
    VALORMAODEOBRA DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_SERVICO PRIMARY KEY (IDSERVICO)
);
ALTER TABLE SERVICO AUTO_INCREMENT = 1;

CREATE TABLE ORDEM_SERVICO_SERVICO (
    ORDEM_SERVICO_ID INT NOT NULL,
    SERVICO_ID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ORDEM_SERVICO_SERVICO PRIMARY KEY (ORDEM_SERVICO_ID, SERVICO_ID),
    CONSTRAINT FK_ORDEM_SERVICO_ORDEM_SERVICO_SERVICO FOREIGN KEY (ORDEM_SERVICO_ID) REFERENCES ORDEM_SERVICO(IDORDEM_SERVICO),
    CONSTRAINT FK_SERVICO_ORDEM_SERVICO_SERVICO FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(IDSERVICO)
);

CREATE TABLE PECAS (
    IDPECA INT AUTO_INCREMENT,
    NOMEPECA VARCHAR(45) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_PECA PRIMARY KEY (IDPECA)
);
ALTER TABLE PECAS AUTO_INCREMENT = 1;

CREATE TABLE ORDEM_SERVICO_PECA (
    ORDEM_SERVICO_PECA_ID INT NOT NULL,
    PECA_ID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ORDEM_SERVICO_PECA PRIMARY KEY (ORDEM_SERVICO_PECA_ID, PECA_ID),
    CONSTRAINT FK_ORDEM_SERVICO_ORDEM_SERVICO_PECA FOREIGN KEY (ORDEM_SERVICO_PECA_ID) REFERENCES ORDEM_SERVICO(IDORDEM_SERVICO),
    CONSTRAINT FK_PECA_ORDEM_SERVICO_PECA FOREIGN KEY (PECA_ID) REFERENCES PECAS(IDPECA)
);

-- Cliente
INSERT INTO CLIENTE (CPF, NOME, ENDEREÇO, EMAIL, TELEFONE) VALUES
('11122233344', 'João Silva', 'Rua A, 123', 'joao.silva@email.com', '999999999'),
('22233344455', 'Maria Santos', 'Rua B, 456', 'maria.santos@email.com', '888888888'),
('33344455566', 'Carlos Lima', 'Rua C, 789', 'carlos.lima@email.com', '777777777');

-- Veiculo
INSERT INTO VEICULO (PLACA, MODELO, ANO, MARCA, CLIENTE_ID) VALUES
('ABC1234', 'Civic', 2020, 'Honda', 1),
('DEF5678', 'Corolla', 2019, 'Toyota', 2),
('GHI9012', 'Golf', 2018, 'Volkswagen', 3);

-- Mecanico
INSERT INTO MECANICO (CPF, NOME, EMAIL, ENDEREÇO, TELEFONE, ESPECIALIDADE) VALUES
('11111111111', 'Pedro Ferreira', 'pedro.ferreira@email.com', 'Rua D, 100', '666666666', 'Motor'),
('22222222222', 'Ana Costa', 'ana.costa@email.com', 'Rua E, 200', '555555555', 'Suspensão'),
('33333333333', 'Lucas Mendes', 'lucas.mendes@email.com', 'Rua F, 300', '444444444', 'Freios');

-- Equipe
INSERT INTO EQUIPE (NOMEEQUIPE) VALUES
('Equipe 1'),
('Equipe 2');

-- Equipe_Mecanico
INSERT INTO EQUIPE_MECANICO (EQUIPE_ID, MECANICO_ID) VALUES
(1, 1),
(1, 2),
(2, 3);

-- Ordem_Servico
INSERT INTO ORDEM_SERVICO (DATA_ENTRADA, DATA_SAIDA, STATUS, VALOR_TOTAL, VEICULO_ID, MECANICOS_ID) VALUES
('2025-02-01', '2025-02-05', 'FINALIZADO', 1500.00, 1, 1),
('2025-02-10', NULL, 'EM ESPERA', 800.00, 2, 2),
('2025-02-15', '2025-02-20', 'FINALIZADO', 1200.00, 3, 2);

-- Servico
INSERT INTO SERVICO (DESCRICAO, VALORMAODEOBRA) VALUES
('Troca de óleo', 100.00),
('Alinhamento', 80.00),
('Revisão geral', 500.00);

-- Ordem_Servico_Servico
INSERT INTO ORDEM_SERVICO_SERVICO (ORDEM_SERVICO_ID, SERVICO_ID, QUANTIDADE, VALOR_TOTAL) VALUES
(1, 1, 1, 100.00),
(2, 2, 2, 160.00),
(3, 3, 1, 500.00);

-- Pecas
INSERT INTO PECAS (NOMEPECA, VALOR) VALUES
('Filtro de óleo', 50.00),
('Pastilha de freio', 150.00),
('Correia dentada', 200.00);

-- Ordem_Servico_Peca
INSERT INTO ORDEM_SERVICO_PECA (ORDEM_SERVICO_PECA_ID, PECA_ID, QUANTIDADE, VALOR_TOTAL) VALUES
(1, 1, 2, 100.00),
(2, 2, 1, 150.00),
(3, 3, 1, 200.00);

-- RETORNA O NOME DA PEÇA E SE VALOR COM UM REAJUSTE DE 10%
SELECT P.NOMEPECA, P.VALOR*1.10 AS VALOR_REAJUSTE FROM PECAS P;

-- RETORNA O NOME DO CLIENTE, A PLACA DO CARRO, A DATA DE ENTRADA NA OFICINA, O VALOR TOTAL DA ORDEM DE SERVIÇO
-- PARA O STATUS DE FINALIZADO E CUJO VALOR TOTAL É SUPERIOR A 1000 REAIS ORDENANDO PELO NOME DO CLIENTE
SELECT C.NOME, V.PLACA, OS.DATA_ENTRADA, OS.VALOR_TOTAL FROM CLIENTE C 
JOIN VEICULO V ON C.IDCLIENTE = V.CLIENTE_ID JOIN ORDEM_SERVICO OS ON V.IDVEICULO = OS.VEICULO_ID
WHERE OS.STATUS = 'FINALIZADO' AND OS.VALOR_TOTAL > 1000.00 ORDER BY C.NOME;

-- RETORNA O NÚMERO DA ORDEM DE SERVIÇO, SEU STATUS, A DESCRIÇÃO DO SERVIÇO E O VALOR DA MÃO DE OBRA PARA SERVIÇOS ACIMA DE
-- 100 REAIS
SELECT OS.IDORDEM_SERVICO, OS.STATUS, S.DESCRICAO, S.VALORMAODEOBRA FROM ORDEM_SERVICO OS
JOIN ORDEM_SERVICO_SERVICO OSS ON OS.IDORDEM_SERVICO = OSS.ORDEM_SERVICO_ID 
JOIN SERVICO S ON OSS.SERVICO_ID = S.IDSERVICO
HAVING S.VALORMAODEOBRA > 100.00;